### ISSUE TITLE
UPS: add support to NegotiatedRatesIndicator

### ISSUE THREAD

**Issue by embedded1** [benweatherman/python-ship#20]
I couldn't find a way adding this to the RateWS.wsdl file:

<RateInformation>
<NegotiatedRatesIndicator/>
</RateInformation>

Can you help me out with this one?

Thanks

**Comment by benweatherman** [comment]
Are you only trying to modify the WSDL? You could submit a PR with the desired changes to https://github.com/benweatherman/python-ship/blob/master/wsdl/ups/RateWS.wsdl

I'm fairly sure that WSDL is quite out of date so if you want to update to the latest, that'd be 👍

**Comment by embedded1** [comment]
Where can I get the latest wdsl file?

**Comment by benweatherman** [comment]
It's usually included in the UPS developer kit that's downloaded from their dev portal

**Comment by benweatherman** [comment]
OK, seems like it might've just not been enabled for your account.
